title: Jeffrey Li
logo: /assets/images/headshot.png
# description: text below image

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

show_downloads: true
theme: jekyll-theme-minimal